### ISSUE TITLE
Implement Factories for most important models and use for seeding

### ISSUE THREAD

**Issue by Kamieljv** [Kamieljv/watkanikdoen-app#98]
https://laravel.com/docs/11.x/eloquent-factories

**Comment by ItaSsa** [comment]
**2024/05/13** 
  _Done:_ 
       - Commit hash: aaa87392e1390de925e886f3ae85f5fe73d9f614  
              - First version of factory to Acties table. Adding a new seeder but the past seed could be used just changing the file DatabaseSeeder.
    _To do:_
        - Insert  new factories and relationships between them;
        - Improve rules to generate dummy data to Acties table.

**Comment by ItaSsa** [comment]
**2024/05/20**
-- Last Commit hash - commit 2cc71caa6824c187290facae2aabe593afa031ce
- Implemented factories to: Actie, Organizer,Category,Report,Theme.
- Implemented seeds to tables: acties,organizers,categories,reports, theme,actie_category,actie_organizer,actie_theme,organizer_theme,reports.
